package cn.edu.swpu.cins.openday.enums.service;

public enum UserServiceResultEnum {
	ADD_USER_SUCCESS,
	ADD_USER_FAILED,
	EXISTED_USERNAME_AND_MAIL,
	EXISTED_USERNAME,
	EXISTED_MAIL,
	ENABLE_TOKEN_SUCCESS,
	ENABLE_TOKEN_INVALID,
	ENABLE_TOKEN_TIMEOUT,
	SIGN_OUT_SUCCESS,
	SIGN_OUT_FAILED,
	ADD_USER_USABLE,
//	登陆返回的status
	PASSWORD_NOT_SAME,
	LOGIN_SUCCESS,
	USER_NOT_EXIST,
	CACHE_FAILED
}
