package cn.edu.swpu.cins.openday.enums;

public enum CacheResultEnum {
	SAVE_FAILED, ENABLE_TOKEN_SUCCESS, ENABLE_TOKEN_INVALID, ENABLE_TOKEN_TIMEOUT, REMOVE_TOKEN_SUCCESS, REMOVE_TOKEN_FAILED, REMOVE_SUCCESS, REMOVE_FAILED, SAVE_SUCCESS
}
